---

stages:
  - build
  - test

build:
  stage: build
  image: node
  script:
    - cd React/MatriLED
    - npm install
    - npm build
  artifacts:
    expire_in: 1 hour
    paths:
      - React/MatriLED/build
      - React/MatriLED/node_modules/
  only:
    - Mobile-Application

test:
  stage: test
  image: node
  script:
    - CI=true npm test
  only:
    - Mobile-Application

...
