---

stages:
  - build

build:
  stage: build
  image: node:alpine
  script:
    - cd React/MatriLED
    - npm ci
  artifacts:
    expire_in: 1 hour
    paths:
      - React/MatriLED/node_modules
  only:
    - Mobile-Application

...
