---

stages:
  - build

build:
  stage: build
  image: debian:latest
  script:
    - apt-get update && apt-get install -y curl arduino
    - curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
    - /builds/curs3_w4ll/matriled/bin/arduino-cli core install arduino:avr
    - /builds/curs3_w4ll/matriled/bin/arduino-cli compile -b arduino:avr:uno --build-path "Arduino/MatriLED/build" -v "Arduino/MatriLED/Matriled.ino"

...
