---

stages:
  - build
  - test

build:
  stage: build
  image: node
  script:
    - npm install
    - npm build
    artifacts:
      expire_in: 1 hour
      paths:
        - build
        - node_modules/

test:
  stage: test
  image: node
  script:
    - CI=true npm test

...
