---

stages:
  - build

build:
  stage: build
  image: debian:latest
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh
    - arduino-cli compile -b arduino:avr:uno --build-path "Arduino/MatriLED/build" -v "Arduino/MatriLED/Matriled.ino"

...
